/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ExampleModuleInterface extends ethers.utils.Interface {
  functions: {
    "causeRevert()": FunctionFragment;
    "logEvent()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "causeRevert",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "logEvent", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "causeRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logEvent", data: BytesLike): Result;

  events: {
    "ExampleModuleEvent(string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExampleModuleEvent"): EventFragment;
}

export type ExampleModuleEventEvent = TypedEvent<
  [string] & { message: string }
>;

export class ExampleModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ExampleModuleInterface;

  functions: {
    causeRevert(overrides?: CallOverrides): Promise<[void]>;

    logEvent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  causeRevert(overrides?: CallOverrides): Promise<void>;

  logEvent(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    causeRevert(overrides?: CallOverrides): Promise<void>;

    logEvent(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "ExampleModuleEvent(string)"(
      message?: null
    ): TypedEventFilter<[string], { message: string }>;

    ExampleModuleEvent(
      message?: null
    ): TypedEventFilter<[string], { message: string }>;
  };

  estimateGas: {
    causeRevert(overrides?: CallOverrides): Promise<BigNumber>;

    logEvent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    causeRevert(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    logEvent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
